import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Context } from '@/shared/context/contexts'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { data: session } = useSession()
  const { replace } = useRouter()

  if (session && session.user) {
    replace('/dashboard')
  }

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Context>{children}</Context>
      </body>
    </html>
  )
}
