import { Header } from '@/components'
import LoggedProvider from '@/shared/context/session'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Mission Store',
  description: 'Generated by create next app',
}

export default function SessionLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <LoggedProvider>
      <Header />
      {children}
    </LoggedProvider>
  )
}
